### ISSUE TITLE
can someone help me why is this?

### ISSUE THREAD

**Issue by faizyoshio** [WMGameLive/AutoFishing#4]
![image](https://github.com/WMGameLive/AutoFishing/assets/79403336/56f68490-be56-4efe-8e12-a7d50d2e126d)

```
[09:37:10 WARN]: [AutoFishing] Task #3787 for AutoFishing v1.8 generated an exception
java.lang.NoSuchMethodError: 'net.minecraft.world.level.World net.minecraft.server.level.EntityPlayer.dM()'
        at wm.vdr.autofishing.Listeners.doRightClick(Listeners.java:57) ~[AutoFishing-1.8_3.jar:?]
        at wm.vdr.autofishing.Listeners.access$100(Listeners.java:18) ~[AutoFishing-1.8_3.jar:?]
        at wm.vdr.autofishing.Listeners$1.run(Listeners.java:37) ~[AutoFishing-1.8_3.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1470) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by WMGameLive** [comment]
Your are running on 1.20.2, please use version 1.7, 1.8 is for 1.20.4.
https://www.spigotmc.org/resources/1-18-1-20-4-autofishing.100510/history

**Comment by faizyoshio** [comment]
thanks a lot, owner

**Comment by faizyoshio** [comment]
doneee, thanks owner for teach me, because before i dont now how to download old version. thanks a lotttt

**Comment by WMGameLive** [comment]
You're welcome.
